### ISSUE TITLE
Need support for zeebe >= 1.0.0

### ISSUE THREAD

**Issue by kousher-alam** [crossid/zeebe-mongo-exporter#6]
Hi, i'm using following version of the zeebe ecosystem 
- zeebe:1.0.0
- zeebe-simple-monitor:2.0.0
- operate:1.0.0
- hazelcast-exporter-1.0.0

but when I add mongodb exporter zeebe-mongo-exporter.jar with the following configuration 

```yml
mongo:
        className: io.crossid.zeebe.exporter.MongoExporter
        jarPath: exporters/zeebe-mongo-exporter.jar

        args:
          url: mongodb://localhost:27017
          dbName: zeebe
          bulk:
            delay: 5
            size: 1000
          col:
            prefix: zeebe-record
            createCollections: true
            command: false
            event: true
            rejection: false
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: true
            messageSubscription: true
            variable: true
            variableDocument: true
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
            timers: true
```

then hazelcast-exporter and mongodb exporter both don't work. in zeebe I just got this log about mongodb 
![image](https://user-images.githubusercontent.com/78843376/122180905-abfa4580-ceaa-11eb-90c7-25dc588e17ec.png)

But without mongodb exporter everything was fine. 

so what is the problem and how can we solve the problem ??
